### ISSUE TITLE
With PHP C extension getting considerably worse peformance

### ISSUE THREAD

**Issue by marcusds** [maxmind/MaxMind-DB-Reader-php#32] opened 2015-12-04 22:10 UTC
I installed the PHP C extension in an environment where every millisecond matters and it loads and it works, but we are getting far worse performance with the extension enabled compared to just using straight PHP.

With the C extension it can take anywhere from 1.5 s to 0.005. Most of the time it is over 0.8s.
With the C extensions disabled using just the PHP classes the performance is constant around 0.15s.

Running a script from command line with a fixed IP address with the classes installed from Composer.

Here is my test code:

    <?php
    $t = microtime(true);
    require 'vendor/autoload.php';
    $reader = new \GeoIp2\Database\Reader(__DIR__ . '/GeoLite2-City.mmdb');
    $ip = '8.8.8.8'; // Actually using my own IP, but don't want to include that here.
    $record = $reader->city($ip);
    echo microtime(true) - $t;
    ?>

Is there anything I could have done wrong? Any help you can provide?

**Comment by oschwald** [comment] 2015-12-04 22:34
This isn't likely to be a good benchmark unless your use case is to load the script from the command line and do exactly one IP lookup. That said, here are the times on my machine using PHP 5.6.11:

* with `maxminddb`: 12-15 ms
* without `maxminddb`: 30-4 0ms

**Comment by marcusds** [comment] 2015-12-04 22:46
We are only doing one lookup per run, but it is being run from Apache.

It's odd your results were more inline with what one would expect, but mine are so far off.

**Comment by oschwald** [comment] 2016-01-07 16:10
Did you ever figure this out? I am going to close the issue since we cannot reproduce it, but I am happy to re-open if you have more information.

**Closed by oschwald** 2016-01-07 16:10 UTC

**Comment by marcusds** [comment] 2016-01-12 15:22
We recently moved the project from a VPS to dedicated hardware. You closing this ticket reminded me to try again the C extension again.
On the new hardware 1000 runs takes 1.8 seconds without the extension with extension it takes 0.16 seconds. So a massive improvement.

Must have been the VPS.

Thanks

**Comment by oschwald** [comment] 2016-01-12 15:24
Great. Good to hear.
