### ISSUE TITLE
PHPStan v2 errors

### ISSUE THREAD

**Issue by JulianAtkins** [maxmind/MaxMind-DB-Reader-php#176] opened 2024-11-16 22:29 UTC
PHPStan v2 has been released and this new version comes up with two errors:

```
 ------ -------------------------------------------------------------------------------------------------------- 
  Line   src/MaxMind/Db/Reader/Decoder.php                                                 
 ------ -------------------------------------------------------------------------------------------------------- 
  111    Parameter #3 $size of method MaxMind\Db\Reader\Decoder::decodeByType() expects int<0, max>, int given.  
         🪪  argument.type                                                                                       
  384    Parameter #1 $num1 of function bcmul expects numeric-string, string given.                              
         🪪  argument.type                                                                                       
 ------ -------------------------------------------------------------------------------------------------------- 
```

I tried to solve them, but I am not familiar with the MaxMind data structure, so I failed :)

The first error, it about the function `sizeFromCtrlByte()` which returns an `int $size` that is then passed as a parameter to `decodeByType()`, which requires that the type is `int<0, max>` (and not just `int`).

The second error, is about the `bcmul()` function that expects a numeric string and not just any string.

**Comment by oschwald** [comment] 2024-11-18 15:16
I cannot reproduce this:

```
$ php vendor/bin/phpstan --version
PHPStan - PHP Static Analysis Tool 2.0.2
$ /usr/bin/php vendor/bin/phpstan analyze
Note: Using configuration file /home/greg/MaxMind/MaxMind-DB-Reader-php/phpstan.neon.
 9/9 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%



 [OK] No errors
```

We also run `phpstan` from GitHub Actions.

**Comment by oschwald** [comment] 2024-11-18 19:36
Yes, I see various warnings. We only test at level 6 at this point.

Is there a particular issue this is causing?

**Comment by oschwald** [comment] 2024-12-04 20:22
I am going to close this. If there was an issue in the typing that caused an unexpected warning to show up for users of this library in their own code, that would be a legitimate bug that should be fixed. However, these warnings are internal to the package and don't affect the public API. If we decide to increase our PHPStan level, we would probably do it for all our PHP repos at once.

**Closed as completed by oschwald** 2024-12-04 20:22 UTC
