### ISSUE TITLE
PHP7 support

### ISSUE THREAD

**Issue by Stajor** [maxmind/MaxMind-DB-Reader-php#40] opened 2016-05-03 05:53 UTC
I got an error after installation
```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/maxminddb.so' - /usr/lib/php/20151012/maxminddb.so: undefined symbol: zval_used_for_init in Unknown on line 0
```
Any suggestion?
PHP 7.0.6

**Comment by oschwald** [comment] 2016-05-03 14:17
PHP 7 is supported since 1.1.0. What version of maxminddb are you trying to compile?

**Comment by oschwald** [comment] 2016-05-27 15:19
Closing as we are not able to reproduce the issue. I am happy to reopen it given more information.

**Closed by oschwald** 2016-05-27 15:19 UTC
